# AUTO-GENERATED FILE — do not edit by hand
# Generated by generate_from_schema.py based on ops_schema.py
from __future__ import annotations
from typing import Optional, List, Any, Dict
from ops_schema import DTypeId

class OpsMixin:
    """
    Generated mixin with one method per op.
    Subclasses must implement:
      - _coerce_payload(self, op: str, payload: Dict[str, Any]) -> Dict[str, Any]
      - _emit(self, op: str, **payload) -> None
    """

    def NOOP(self) -> None:
        self._emit("NOOP")

    def LINEAR(self, *, x: Any, weight: Any, out: Any, bias: Optional[Any] = None) -> None:
        payload = self._coerce_payload("LINEAR", locals())
        self._emit("LINEAR", **payload)

    def RMS_NORM(self, *, x: Any, weight: Any, out: Any, eps: float = 1e-05) -> None:
        payload = self._coerce_payload("RMS_NORM", locals())
        self._emit("RMS_NORM", **payload)

    def ROPE_APPLY(self, *, q_in: Any, k_in: Any, q_out: Any, k_out: Any, head_dim: int, pos: Any, freqs: Optional[Any] = None, traditional: bool = False, base: Optional[float] = 500000.0, scale: float = 1.0) -> None:
        payload = self._coerce_payload("ROPE_APPLY", locals())
        self._emit("ROPE_APPLY", **payload)

    def SDPA(self, *, q: Any, k: Any, v: Any, out: Any, scale: float = 1.0, mask: Optional[Any] = None, causal: bool = False) -> None:
        payload = self._coerce_payload("SDPA", locals())
        self._emit("SDPA", **payload)

    def ADD(self, *, a: Any, b: Any, out: Any) -> None:
        payload = self._coerce_payload("ADD", locals())
        self._emit("ADD", **payload)

    def MUL(self, *, a: Any, b: Any, out: Any) -> None:
        payload = self._coerce_payload("MUL", locals())
        self._emit("MUL", **payload)

    def SILU(self, *, x: Any, out: Any) -> None:
        payload = self._coerce_payload("SILU", locals())
        self._emit("SILU", **payload)

    def RESHAPE(self, *, x: Any, out: Any, shape: List[int]) -> None:
        payload = self._coerce_payload("RESHAPE", locals())
        self._emit("RESHAPE", **payload)

    def TRANSPOSE(self, *, x: Any, out: Any, perm: List[int]) -> None:
        payload = self._coerce_payload("TRANSPOSE", locals())
        self._emit("TRANSPOSE", **payload)

    def CONTIGUOUS(self, *, x: Any, out: Any) -> None:
        payload = self._coerce_payload("CONTIGUOUS", locals())
        self._emit("CONTIGUOUS", **payload)

    def GATHER(self, *, table: Any, ids: Any, out: Any) -> None:
        payload = self._coerce_payload("GATHER", locals())
        self._emit("GATHER", **payload)

    def SLICE(self, *, x: Any, out: Any, axis: int | Any, start: int | Any, length: int | Any) -> None:
        payload = self._coerce_payload("SLICE", locals())
        self._emit("SLICE", **payload)

    def CAST(self, *, x: Any, out: Any, dtype: DTypeId | str = 'f16') -> None:
        payload = self._coerce_payload("CAST", locals())
        self._emit("CAST", **payload)

    def QUANTIZED_LINEAR(self, *, x: Any, w: Any, scales: Any, out: Any, biases: Optional[Any] = None, bias: Optional[Any] = None, group_size: int = 64, bits: int = 4, mode: str = 'affine', out_dtype: DTypeId | str = 'f32') -> None:
        payload = self._coerce_payload("QUANTIZED_LINEAR", locals())
        self._emit("QUANTIZED_LINEAR", **payload)

    def CONCAT(self, *, a: Any, b: Any, out: Any, axis: int = 0) -> None:
        payload = self._coerce_payload("CONCAT", locals())
        self._emit("CONCAT", **payload)

    def FULL(self, *, out: Any, shape: List[int], v: float = 0.0, dtype: DTypeId | str = 'f16') -> None:
        payload = self._coerce_payload("FULL", locals())
        self._emit("FULL", **payload)

    def ZEROS(self, *, out: Any, shape: List[int], dtype: DTypeId | str = 'f16') -> None:
        payload = self._coerce_payload("ZEROS", locals())
        self._emit("ZEROS", **payload)

    def ONES(self, *, out: Any, shape: List[int], dtype: DTypeId | str = 'f16') -> None:
        payload = self._coerce_payload("ONES", locals())
        self._emit("ONES", **payload)

    def ARGMAX(self, *, x: Any, out: Any, axis: int = -1) -> None:
        payload = self._coerce_payload("ARGMAX", locals())
        self._emit("ARGMAX", **payload)

    def SLICE_UPDATE(self, *, dst: Any, update: Any, axis: int | Any, start: int | Any, length: int | Any) -> None:
        payload = self._coerce_payload("SLICE_UPDATE", locals())
        self._emit("SLICE_UPDATE", **payload)

    def QUANTIZED_GATHER(self, *, table_q: Any, scales: Any, ids: Any, out: Any, biases: Optional[Any] = None, group_size: int = 64, bits: int = 4, mode: str = 'affine', out_dtype: DTypeId | str = 'f32') -> None:
        payload = self._coerce_payload("QUANTIZED_GATHER", locals())
        self._emit("QUANTIZED_GATHER", **payload)
